baseURL: http://adamliliemark.github.io
languageCode: en-us
title: Adam CL

theme: "PaperMod"

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 30
    # - identifier: search
    #   name: search
    #   url: /search/
    #   weight: 30

params:
    ShowReadingTime: true
    profileMode:
        enabled: true
        title: "Adam CL" # optional default will be site title
        #imageUrl: "<image link>" # optional
        #imageTitle: "<title of image as alt>" # optional
    socialIcons:
    - name: github
      url: https://github.com/adamliliemark
    - name: linkedin
      url: https://www.linkedin.com/in/adamliliemark/
    - name: email
      url: mailto:placeholder@mail.com

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary